/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpcb_prot.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
rpcbprog_3(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		rpcb rpcbproc_set_3_arg;
		rpcb rpcbproc_unset_3_arg;
		rpcb rpcbproc_getaddr_3_arg;
		rpcb_rmtcallargs rpcbproc_callit_3_arg;
		char *rpcbproc_uaddr2taddr_3_arg;
		netbuf rpcbproc_taddr2uaddr_3_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case RPCBPROC_SET:
		_xdr_argument = (xdrproc_t) xdr_rpcb;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) rpcbproc_set_3_svc;
		break;

	case RPCBPROC_UNSET:
		_xdr_argument = (xdrproc_t) xdr_rpcb;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) rpcbproc_unset_3_svc;
		break;

	case RPCBPROC_GETADDR:
		_xdr_argument = (xdrproc_t) xdr_rpcb;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) rpcbproc_getaddr_3_svc;
		break;

	case RPCBPROC_DUMP:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_rpcblist_ptr;
		local = (char *(*)(char *, struct svc_req *)) rpcbproc_dump_3_svc;
		break;

	case RPCBPROC_CALLIT:
		_xdr_argument = (xdrproc_t) xdr_rpcb_rmtcallargs;
		_xdr_result = (xdrproc_t) xdr_rpcb_rmtcallres;
		local = (char *(*)(char *, struct svc_req *)) rpcbproc_callit_3_svc;
		break;

	case RPCBPROC_GETTIME:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_u_int;
		local = (char *(*)(char *, struct svc_req *)) rpcbproc_gettime_3_svc;
		break;

	case RPCBPROC_UADDR2TADDR:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_netbuf;
		local = (char *(*)(char *, struct svc_req *)) rpcbproc_uaddr2taddr_3_svc;
		break;

	case RPCBPROC_TADDR2UADDR:
		_xdr_argument = (xdrproc_t) xdr_netbuf;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) rpcbproc_taddr2uaddr_3_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
rpcbprog_4(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		rpcb rpcbproc_set_4_arg;
		rpcb rpcbproc_unset_4_arg;
		rpcb rpcbproc_getaddr_4_arg;
		rpcb_rmtcallargs rpcbproc_bcast_4_arg;
		char *rpcbproc_uaddr2taddr_4_arg;
		netbuf rpcbproc_taddr2uaddr_4_arg;
		rpcb rpcbproc_getversaddr_4_arg;
		rpcb_rmtcallargs rpcbproc_indirect_4_arg;
		rpcb rpcbproc_getaddrlist_4_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case RPCBPROC_SET:
		_xdr_argument = (xdrproc_t) xdr_rpcb;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) rpcbproc_set_4_svc;
		break;

	case RPCBPROC_UNSET:
		_xdr_argument = (xdrproc_t) xdr_rpcb;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) rpcbproc_unset_4_svc;
		break;

	case RPCBPROC_GETADDR:
		_xdr_argument = (xdrproc_t) xdr_rpcb;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) rpcbproc_getaddr_4_svc;
		break;

	case RPCBPROC_DUMP:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_rpcblist_ptr;
		local = (char *(*)(char *, struct svc_req *)) rpcbproc_dump_4_svc;
		break;

	case RPCBPROC_BCAST:
		_xdr_argument = (xdrproc_t) xdr_rpcb_rmtcallargs;
		_xdr_result = (xdrproc_t) xdr_rpcb_rmtcallres;
		local = (char *(*)(char *, struct svc_req *)) rpcbproc_bcast_4_svc;
		break;

	case RPCBPROC_GETTIME:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_u_int;
		local = (char *(*)(char *, struct svc_req *)) rpcbproc_gettime_4_svc;
		break;

	case RPCBPROC_UADDR2TADDR:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_netbuf;
		local = (char *(*)(char *, struct svc_req *)) rpcbproc_uaddr2taddr_4_svc;
		break;

	case RPCBPROC_TADDR2UADDR:
		_xdr_argument = (xdrproc_t) xdr_netbuf;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) rpcbproc_taddr2uaddr_4_svc;
		break;

	case RPCBPROC_GETVERSADDR:
		_xdr_argument = (xdrproc_t) xdr_rpcb;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) rpcbproc_getversaddr_4_svc;
		break;

	case RPCBPROC_INDIRECT:
		_xdr_argument = (xdrproc_t) xdr_rpcb_rmtcallargs;
		_xdr_result = (xdrproc_t) xdr_rpcb_rmtcallres;
		local = (char *(*)(char *, struct svc_req *)) rpcbproc_indirect_4_svc;
		break;

	case RPCBPROC_GETADDRLIST:
		_xdr_argument = (xdrproc_t) xdr_rpcb;
		_xdr_result = (xdrproc_t) xdr_rpcb_entry_list_ptr;
		local = (char *(*)(char *, struct svc_req *)) rpcbproc_getaddrlist_4_svc;
		break;

	case RPCBPROC_GETSTAT:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_rpcb_stat_byvers;
		local = (char *(*)(char *, struct svc_req *)) rpcbproc_getstat_4_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (RPCBPROG, RPCBVERS);
	pmap_unset (RPCBPROG, RPCBVERS4);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, RPCBPROG, RPCBVERS, rpcbprog_3, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (RPCBPROG, RPCBVERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, RPCBPROG, RPCBVERS4, rpcbprog_4, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (RPCBPROG, RPCBVERS4, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, RPCBPROG, RPCBVERS, rpcbprog_3, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (RPCBPROG, RPCBVERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, RPCBPROG, RPCBVERS4, rpcbprog_4, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (RPCBPROG, RPCBVERS4, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
